### ISSUE TITLE
Glitch in the Lab?

### ISSUE THREAD

**Issue by BenHaugen** [learn-co-curriculum/js-beatles-loops-lab#31] opened 2018-09-13 18:07 UTC
Hello, when I try to check my work in the beatles lab, the system seems to malfunction. When I type "learn" this is what returns:

> js-beatles-loops-lab@0.1.0 test /home/BenHaugen/js-beatles-loops-lab-js-apply-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 1   __,------,
<--- Last few GCs --->
 0   _~|_( ^ .^)
[963:0x3d3a790]    48811 ms: Mark-sweep 1558.0 (1602.4) -> 1557.4 (1616.4) MB, 1
487.0 / 0.0 ms  allocation failure GC in old space requested
[963:0x3d3a790]    50233 ms: Mark-sweep 1557.4 (1616.4) -> 1557.2 (1585.4) MB, 1421.5 / 0.0 ms  last resort GC in old space requested
[963:0x3d3a790]    51620 ms: Mark-sweep 1557.2 (1585.4) -> 1557.2 (1585.4) MB, 1387.1 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x287c39425879 <JSObject>
    1: johnLennonFacts(aka johnLennonFacts) [about:blank:~15] [pc=0x2037a1397ee0](this=0x3d8940b022d1 <undefined>)
    2: arguments adaptor frame: 1->0
    3: /* anonymous */ [/home/BenHaugen/js-beatles-loops-lab-js-apply-000/test/index-test.js:11] [bytecode=0x88f0a0fe411 offset=17](this=0x2c2b5cf18679 <Context map = 0x39a1a6540bb1>)
    4: callFn [/home/BenHaugen/js-beatles-loops-lab-js-apply-0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x8c21ec [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/bin/node]
 6: 0xd4b153 [/usr/bin/node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
 8: 0x2037a12042fd
Aborted (core dumped)
npm ERR! Test failed.  See above for more details.
[18:05:46] (master) js-beatles-loops-lab-js-apply-000
// ♥ /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/reporter.rb:47:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/reporter.rb:13:in `report'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/runner.rb:44:in `report_and_clean'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/runner.rb:21:in `block in run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/runner.rb:20:in `fork'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/lib/learn_test/runner.rb:20:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.5.6/bin/learn-test:68:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'

**Comment by drakeltheryuujin** [comment] 2018-10-05 18:34
Hi there!  

[Raising issues on GitHub][raise] should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). 

If Learn is misbehaving, please direct your bug report to bugs@learn.co.  If it is an environment issue, we unfortunately do not have the capacity to support that at this time. I would recommend googling around about the problem. 

I'm having difficulty reproducing this issue, so I'm going to close it for now. If I've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson

As always, thanks for contributing! 💙

**Closed as completed by drakeltheryuujin** 2018-10-05 18:34 UTC
Labels: Product

**Comment by ariccio** [comment] 2019-04-08 23:30
I'm not hitting this issue, but since I'm a C++ guy and I love reading chromium source code (really, it's the best C++ out there), I'll leave my two cents.

Basically, the system is running out of memory. I'll bet your loop never completes, and you end up with a bazillion elements. The runtime (v8) tries to make a bunch of space for your array, and fails:
```
<--- Last few GCs --->
0 ~|( ^ .^)
[963:0x3d3a790] 48811 ms: Mark-sweep 1558.0 (1602.4) -> 1557.4 (1616.4) MB, 1
487.0 / 0.0 ms allocation failure GC in old space requested
```
...and then tries one last time to free up some memory:
```
[963:0x3d3a790] 50233 ms: Mark-sweep 1557.4 (1616.4) -> 1557.2 (1585.4) MB, 1421.5 / 0.0 ms last resort GC in old space requested
[963:0x3d3a790] 51620 ms: Mark-sweep 1557.2 (1585.4) -> 1557.2 (1585.4) MB, 1387.1 / 0.0 ms last resort GC in old space requested
```

What you see after that is the V8 engine's stacktrace when it panicked and blew itself up:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node::Abort() [/usr/bin/node]
2: 0x8c21ec [/usr/bin/node]
3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
```
You can see [`FatalProcessOutOfMemory` here](https://cs.chromium.org/chromium/src/v8/src/api.cc?q=i::V8::FatalProcessOutOfMemory&sq=package:chromium&g=0&l=370), where it does a bunch of diagnostics to make it easier to debug, then `ReportOOMFailure` calls into a [custom error handler (if present)](https://cs.chromium.org/chromium/src/v8/src/api.cc?type=cs&q=ReportOOMFailure&sq=package:chromium&g=0&l=500), which nodeJS does.
